export const en = {
  nextlanguage: 'RU',
  features: 'Features',
  pricing: 'Pricing',
  support: 'Support',
  join_community: 'Join community',
  badge: 'The most stable network of proxy servers',
  title: 'Turn our proxies into profitable',
  business: ' business',
  get_started_now: 'Get started now',
  ask_a_question: 'Ask a Question',
  total: 'Total',
  now: 'Now',
  proxies: 'Proxies',
  available: 'Available',
  terms_of_use: 'Terms of Use',
  privacy_policy: 'Privacy Policy',
  service: 'Service',
  resources: 'Resources',
  payment: 'Payment',
  integrations: 'Integrations',
  documentation: 'Documentation',
  support_center: 'Support Center',
  partners_investment: 'Partners & Investment',
  connection_status: 'Connection Status',
  check_availability: 'Check Availability',
  placeholders: {
    username: 'Username',
    password: 'Password',
  },
};
