export const ru = {
  nextlanguage: 'EN',
  features: 'Особенности',
  pricing: 'Цены',
  support: 'Поддержка',
  join_community: 'Подключиться',
  badge: 'Самая стабильная сеть прокси-серверов',
  title: 'Превратите наши прокси в прибыльный',
  business: ' бизнес',
  get_started_now: 'Начните всего за 29Р',
  ask_a_question: 'Задать вопрос',
  total: 'Всего',
  now: 'Сейчас',
  proxies: 'Прокси',
  available: 'Доступно',
  terms_of_use: 'Условия использования',
  privacy_policy: 'Политика конфиденциальности',
  service: 'Сервис',
  resources: 'Ресурсы',
  payment: 'Оплата',
  integrations: 'Интеграции',
  documentation: 'Документация',
  support_center: 'Поддержка',
  partners_investment: 'Сотрудничество',
  connection_status: 'Статус Подключения',
  check_availability: 'Проверка доступности',
  placeholders: {
    username: 'Username',
    password: 'Password',
  },
};
